/**
 * Galactic Alpha - Astro + On-Chain Data Joiner
 * 
 * This script combines swap data from the Pipes indexer with astrological
 * conditions from the ephemeris engine to create enriched backtesting data.
 * 
 * Usage:
 *   npm install
 *   npx tsx joinAstro.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

// __dirname is available in CommonJS (which we're using)
// TypeScript might not recognize it, but it works at runtime with tsx
declare const __dirname: string;

/**
 * Interface for swap data entries from the Pipes indexer
 */
interface SwapData {
  block: number;
  txHash: string;
  price: string;
  volume: string;
}

/**
 * Interface for astro data from the ephemeris engine
 */
interface AstroData {
  date: string;
  moon_phase: string;
  mercury_retrograde: boolean;
  jupiter_mars_conjunction: boolean;
  astro_rating: string;
}

/**
 * Interface for enriched swap data with astro information
 */
interface EnrichedSwapData extends SwapData {
  astro: {
    moon_phase: string;
    mercury_retrograde: boolean;
    jupiter_mars_conjunction: boolean;
    astro_rating: string;
  };
}

/**
 * Main function to join swap data with astro data
 */
function main() {
  console.log('🔗 Joining swap data with astrological conditions...\n');
  
  // Read swap data from Pipes indexer
  // Note: swap_data.json is generated by running pipes/indexer.ts
  const swapDataPath = join(__dirname, '../pipes/swap_data.json');
  console.log(`📖 Reading swap data from: ${swapDataPath}`);
  
  let swapData: SwapData[];
  try {
    const swapDataContent = readFileSync(swapDataPath, 'utf-8');
    swapData = JSON.parse(swapDataContent);
    console.log(`   Found ${swapData.length} swap entries`);
  } catch (error) {
    console.error('❌ Error reading swap_data.json:', error);
    console.error('💡 Make sure you have run the Pipes indexer first:');
    console.error('   cd pipes && npm install && npx tsx indexer.ts');
    process.exit(1);
  }
  
  // Read astro data from ephemeris engine
  const astroDataPath = join(__dirname, '../astro/astro_today_index.json');
  console.log(`📖 Reading astro data from: ${astroDataPath}`);
  
  let astroData: AstroData;
  try {
    const astroDataContent = readFileSync(astroDataPath, 'utf-8');
    astroData = JSON.parse(astroDataContent);
    console.log(`   Date: ${astroData.date}`);
    console.log(`   Moon Phase: ${astroData.moon_phase}`);
    console.log(`   Mercury Retrograde: ${astroData.mercury_retrograde ? 'Yes' : 'No'}`);
    console.log(`   Jupiter-Mars Conjunction: ${astroData.jupiter_mars_conjunction ? 'Yes' : 'No'}`);
    console.log(`   Astro Rating: ${astroData.astro_rating}`);
  } catch (error) {
    console.error('❌ Error reading astro_today_index.json:', error);
    console.error('💡 Make sure you have run the astro engine first:');
    console.error('   cd astro && npm install && npx tsx today.ts');
    process.exit(1);
  }
  
  // Join swap data with astro data
  // Each swap entry gets enriched with the astro conditions
  console.log('\n🔗 Enriching swap data with astro conditions...');
  const enriched: EnrichedSwapData[] = swapData.map(entry => ({
    ...entry,
    astro: {
      moon_phase: astroData.moon_phase,
      mercury_retrograde: astroData.mercury_retrograde,
      jupiter_mars_conjunction: astroData.jupiter_mars_conjunction,
      astro_rating: astroData.astro_rating,
    },
  }));
  
  // Ensure output directory exists
  const outputDir = join(__dirname, '../backtest');
  try {
    mkdirSync(outputDir, { recursive: true });
  } catch (error) {
    // Directory might already exist, which is fine
  }
  
  // Write joined data to output file
  const outputPath = join(outputDir, 'swap_astro_joined.json');
  writeFileSync(outputPath, JSON.stringify(enriched, null, 2));
  
  console.log(`\n✅ Successfully joined ${enriched.length} entries with astro data`);
  console.log(`📁 Output written to: ${outputPath}`);
  
  // Show sample output
  if (enriched.length > 0) {
    console.log('\n📄 Sample output (first entry):');
    console.log(JSON.stringify(enriched[0], null, 2));
  }
}

// Run the main function
main();

